js-for-sf-devs/main/default/objects/Bike__c/Bike__c.object-meta.xml
<CustomObject>
    <label>Bike</label>
    <nameField>
        <label>Bike Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bikes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

js-for-sf-devs/main/default/objects/Bike_Gear__c/Bike_Gear__c.object-meta.xml
<CustomObject>
    <label>Bike Gear</label>
    <nameField>
        <displayFormat>GEAR-{0000}</displayFormat>
        <label>Bike Gear Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bike Gears</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

js-for-sf-devs/main/default/objects/Bike_Gear__c/fields/Bike__c.field-meta.xml
<CustomField>
    <fullName>Bike__c</fullName>
    <label>Bike</label>
    <referenceTo>Bike__c</referenceTo>
    <relationshipLabel>Bike Gears</relationshipLabel>
    <relationshipName>Bike_Gears</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

js-for-sf-devs/main/default/objects/Bike_Gear__c/fields/Gear_Type__c.field-meta.xml
<CustomField>
    <fullName>Gear_Type__c</fullName>
    <label>Gear Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Front (Drive)</fullName>
            </value>
            <value>
                <fullName>Rear (Driven)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

js-for-sf-devs/main/default/objects/Bike_Gear_Teeth__c/Bike_Gear_Teeth__c.object-meta.xml
<CustomObject>
    <label>Bike Gear Teeth</label>
    <nameField>
        <label>Tooth Count</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bike Gear Teeth</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

js-for-sf-devs/main/default/objects/Bike_Gear_Teeth__c/fields/Bike_Gear__c.field-meta.xml
<CustomField>
    <fullName>Bike_Gear__c</fullName>
    <label>Bike Gear</label>
    <referenceTo>Bike_Gear__c</referenceTo>
    <relationshipLabel>Bike Gear Teeth</relationshipLabel>
    <relationshipName>Bike_Gear_Teeth</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

js-for-sf-devs/main/default/objects/Bike_Gear_Teeth__c/fields/Number_of_Teeth__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Teeth__c</fullName>
    <formula>VALUE(Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Teeth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

events-and-functions/apex/BikeLightningService.cls
public with sharing class BikeLightningService {

    @AuraEnabled
    public static List<Bike_Gear__c> retrieveBikeGears(String bikeId){

        List<Bike_Gear__c> gears = new List<Bike_Gear__c>();

        if (bikeId != null && bikeId != ''){
            gears = [
                SELECT 
                    Id,
                    Name,
                    Gear_Type__c,
                    (SELECT
                        Id,
                        Name,
                        Number_of_Teeth__c
                    FROM
                        Bike_Gear_Teeth__r
                    ORDER BY
                        Number_of_Teeth__c)
                FROM
                    Bike_Gear__c
                WHERE 
                    Bike__c = : bikeId
            ];
        }

        return gears; 
      
    }

}